---
title: "3_basic_stat"
author: "Bill Chung"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gridExtra)
library(gapminder)
library(gapminder)
library(dplyr)
library(patchwork)
```


# One sample t-test 

- We have control and treament group.
- treatment group took the medication

```{r}
head(sleep)
unique(sleep$group)
y <- sleep$extra[sleep$group == 1]
class(y)

sleep %>% ggplot(aes(x=extra, fill = group)) + geom_histogram() + facet_grid(rows= vars(group))

summary(y)
sd(y)
```


```{r}
par(mfrow=c(2,2))
hist(y)
boxplot(y)
qqnorm(y); qqline(y)
hist(y, prob=TRUE)
lines(density(y), lty=2)
```

## One sample t-test

- Two side t-test
```{r}
t.test(y)
```

- One side t-test
```{r}
t.test(y, alternative="greater")
```

## Simulation

### One by one
```{r}
curve(dnorm(x, 0, 1.8), -4, 4)

# 크기가 10개인 새로운 표본
options(digits = 3)
set.seed(1606)
y_star <- rnorm(10, 0, 1.8)
mean(y_star-0); sd(y_star)
t_star <- mean(y_star-0) / (sd(y_star)/sqrt(length(y_star)))
print(t_star)

y_star <- rnorm(10, 0, 1.8)
mean(y_star-0); sd(y_star)
t_star <- mean(y_star-0) / (sd(y_star)/sqrt(length(y_star)))
print(t_star)

y_star <- rnorm(10, 0, 1.8)
mean(y_star-0); sd(y_star)
t_star <- mean(y_star-0) / (sd(y_star)/sqrt(length(y_star)))
print(t_star)
```

## 10,000 simulation

```{r}
set.seed(1606)
B <- 1e4
n <- 10
xbars_star <- rep(NA, B)
sds_star <- rep(NA, B)
ts_star <- rep(NA, B)
for(b in 1:B){
  y_star <- rnorm(n, 0, 1.789)
  m <- mean(y_star)
  s <- sd(y_star)
  xbars_star[b] <- m
  sds_star[b] <- s
  ts_star[b] <- m / (s/sqrt(n))
}


opar <- par(mfrow=c(2,2))
hist(xbars_star, nclass=100)
abline(v = 0.75, col='red')
hist(sds_star, nclass=100)
abline(v = 1.789, col='red')
hist(ts_star, nclass=100)
abline(v = 1.3257, col='red')
qqnorm(ts_star); qqline(ts_star)
par(opar)
```




## Revisting t-stat 1.3257

```{r}
length(which(ts_star > 1.3257)) / B

# 스튜던트 t 분포
# 다양한 자유도 값에 따른 t 밀도함수
# https://en.wikipedia.org/wiki/Student%27s_t-distribution
# Credit: 권용찬
nlist=c(1,2,5)
x <- seq(-5, 5, 0.05)
y <- matrix(0, nr=length(x), nc=length(nlist))
opar <- par(mfrow=c(2,1))

plot(x, type="n", xlab="x", ylab="P(x)",
     xlim=c(-5,5), ylim=c(0, 0.45))
for( i in 1:length(nlist)){
  y[,i] <- dt(x, df=nlist[i])
  lines(x, y[,i], col=i, lwd=2)
}
lines(x, dnorm(x), col=4, lwd=2)
legend_text <- c(expression(paste(nu,"=1 ")),
                 expression(paste(nu,"=2 ")),
                 expression(paste(nu,"=5 ")),
                 expression(paste(nu,"=",infinity)))
legend("topright", legend=legend_text, lty=1, lwd=2, col=c(1:3,4),
       inset=.05)


nlist=c(1,2,5)
x <- seq(-5, 5, 0.05)
y <- matrix(0, nr=length(x), nc=length(nlist))
plot(x, type="n", xlab="x", ylab="P(x)",
     xlim=c(-5,5), ylim=c(0, 0.45))
for( i in 1:length(nlist)){
  y[,i] <- dt(x, df=nlist[i])
  lines(x, y[,i], col=i, lwd=2)
}
lines(x, dnorm(x), col=4, lwd=2)
legend_text <- c(expression(paste(nu,"=1 ")),
                 expression(paste(nu,"=2 ")),
                 expression(paste(nu,"=5 ")),
                 expression(paste(nu,"=",infinity)))
legend("topright", legend=legend_text, lty=1, lwd=2, col=c(1:3,4), inset=.05)
```



# 8. Meaning of confidence interval

```{r}
set.seed(1606)
(y_star <- rnorm(10, 1, 1.8))
t.test(y_star)$conf.int
(y_star <- rnorm(10, 1, 1.8))
t.test(y_star)$conf.int
(y_star <- rnorm(10, 1, 1.8))
t.test(y_star)$conf.int
```


```{r}
set.seed(1606)
B = 1e2
conf_intervals <-
  data.frame(b=rep(NA, B),
             lower=rep(NA, B),
             xbar=rep(NA, B),
             upper=rep(NA, B))
true_mu <- 1.0
for(b in 1:B){
  (y_star <- rnorm(10, true_mu, 1.8))
  conf_intervals[b, ] = c(b=b,
                          lower=t.test(y_star)$conf.int[1],
                          xbar=mean(y_star),
                          upper=t.test(y_star)$conf.int[2])
}
conf_intervals <- conf_intervals %>%
  mutate(lucky = (lower <= true_mu & true_mu <= upper))

glimpse(conf_intervals)
table(conf_intervals$lucky)
conf_intervals %>% ggplot(aes(b, xbar, col=lucky)) +
  geom_point() +
  geom_errorbar(aes(ymin=lower, ymax=upper)) +
  geom_hline(yintercept=true_mu, col='red')
```



# Central limit theorm

```{r}
hist(c(0, 1), nclass=100, prob=TRUE, main='Individual sleep time increase')
set.seed(1606)
B <- 1e4
n <- 10
xbars_star= rep(NA, B)
for(b in 1:B){
  xbars_star[b] <- mean(sample(c(0,1), size=n, replace=TRUE))
}
hist(xbars_star, nclass=100, main='Sample mean of 10 obs')


opar = par(mfrow=c(2,1))
hist(c(0, 1), nclass=100, prob=TRUE, main='Individual sleep time increase')
hist(xbars_star, nclass=100, main='Sample mean of 10 obs')
```

# Sample size and confidence interval

```{r}
diff(t.test(y)$conf.int)
mean(y)
diff(t.test(y)$conf.int)/2
```

```{r}
#자료의 incremental 가치
opar = par(mfrow=c(1,2))
curve(1/sqrt(x), 1, 1000, log='x', main='s.e. vs sample size')
curve((1/sqrt(x) - 1/sqrt(x+10)) / (1/sqrt(x)), 1, 1000, log='x',
      main='% decrease in s.e. \nwhen adding 10 obs')
```
